### ISSUE TITLE
[BUG] Możliwość przekazania nieprawidłowej daty do funkcji klasy JsonParser

### ISSUE THREAD

**Issue by ImBioMario** [IIS-ZPI/ZPI2021_IO2_Jamraje_Pasiaste#35]
Przez wykorzystanie funkcji LocalDateTime.now() w klasie Tab1Controller istnieje możliwość przekazania niewłaściwej daty dalej do JsonParsera.
Na przykład:
Mija godzina 24:00 dnia 06.07.2022, uruchamiamy nasz program, aby pobrać dane do wyświetlania wykresów i wykonania obliczeń statystycznych wywołuje się funkcja LocalDateTime.now(), która zwraca nam datę 06.07.2022. Ta data jest przekazywana do JsonParser'a w wyniku czego wysyłamy zapytanie do api NBP o dane z sesji z dnia 06.07.2022, która jeszcze się nie odbyła i nie ma o niej informacji (dane udostępniane przez api NBP są aktualizowane codziennie w godzinach 11-12). Wyrzucany jest wyjątek o błędzie parsowania.

**Comment by szatanmilio** [comment]
Poprawione.
